db/migrate/20220829213342_add_first_name_and_last_name_and_age_and_gender_and_document_and_country_to_users.rb, db/schema.rb
Create a migration file to add columns to Users table:
first_name as String
last_name as String
age as Integer
gender as String
document as String
country as String.
Created project Data Base and ran the migration.
=> Added first name, last name, age, gender, document and country to Users table

app/controllers/application_controller.rb
Updated Application Controller with Devise Parameter Sanitizers:
[first_name last_name age gender document country] for Sign Up and Account Update
=> updating application controller with devise parameter sanitizer

app/controllers/users_controller.rb, app/views/users/show.html.erb, test/controllers/users_controller_test.rb
Created Users controller with 'show' method
Created Users view 'show'
=> created users controller and view

Gemfile.lock, app/controllers/bookings_controller.rb, app/controllers/projects_controller.rb, app/models/booking.rb, app/models/project.rb, db/migrate/20220829221821_create_projects.rb, db/migrate/20220829224303_create_bookings.rb, db/schema.rb, test/controllers/bookings_controller_test.rb, test/controllers/projects_controller_test.rb, test/models/booking_test.rb, test/models/project_test.rb
Created project and booking models and controllers.
=> Create project and booking models and controllers

app/controllers/concerns/accessible.rb, config/application.rb, config/routes.rb
- Edited application.rb to load custom sanitizers on boot
- Removed omniauth_callbacks from Routes (for both User and Organization)
=> Updated devise configs for multiple users

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_card.scss, app/views/projects/index.html.erb, app/views/shared/_card.html.erb, db/seeds.rb
added 10 projects using faker (created some random categories)
improved cards - still not fully responsive and the volunteers avatars have to be potisioned better
=> added projects to seed and improved cards

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_utilities.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_home.scss, app/controllers/projects_controller.rb, app/policies/project_policy.rb, app/views/layouts/application.html.erb, app/views/projects/new.html.erb, config/routes.rb
- Created user story: Organization Create New Project
- Created purple Button component
- Created Form component
- Created _utilities.scss with custom CSS classes
=> Finished user story: Organization Create New Project

.vscode/settings.json, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_form.scss, app/controllers/projects_controller.rb, app/javascript/controllers/flatpickr_controller.js, app/javascript/controllers/index.js, app/views/projects/new.html.erb, package.json, yarn.lock
- Installed Flatpickr package
- Created Flatpickr Stimulus Controller
- Implemented Flatpickr for Project creation form
=> Added Flatpickr to Project creation form

app/controllers/projects_controller.rb, app/views/projects/show.html.erb
=> show project

app/controllers/bookings_controller.rb, app/views/projects/index.html.erb, app/views/projects/show.html.erb
=> Add features2

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_card_user_project.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_title.scss, app/assets/stylesheets/components/_utilities.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_project_show.scss, app/assets/stylesheets/pages/_user_show.scss, app/controllers/bookings_controller.rb, app/controllers/projects_controller.rb, app/controllers/users_controller.rb, app/models/booking.rb, app/models/organization.rb, app/models/project.rb, app/models/user.rb, app/policies/user_policy.rb, app/views/projects/index.html.erb, app/views/projects/new.html.erb, app/views/projects/show.html.erb, app/views/shared/_card.html.erb, app/views/shared/_card_user_project.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20220901183455_remove_user_id_and_project_id_from_bookings.rb, db/migrate/20220901183931_add_user_ref_and_project_ref_to_bookings.rb, db/schema.rb
- Migration to fix Booking references for User and Project 
- Stablished models relationships
- Created basic functionality and core visuals of User Show page
- Create card component for User Show page
=> Finished basic functionality of user show page

app/assets/stylesheets/pages/_project_show.scss, app/controllers/bookings_controller.rb, app/views/projects/show.html.erb, app/views/shared/_card.html.erb, db/seeds.rb
this is the code for the show page : IF THERE IS ANYTHING CONFLICTING PLEASE CHECK IT TO NOT DELETE AGAIN
<div class="container">
<h1 class= "project-header"><strong> <%= @project.name %></strong></h1>
</div>
<div class="container">
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
<div class="carousel-inner">
<div class="carousel-item active">
</div>
<div class="carousel-item">
</div>
<div class="carousel-item">
</div>
</div>
<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
<span class="carousel-control-prev-icon" aria-hidden="true"></span>
<span class="visually-hidden">Previous</span>
</button>
<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" …
=> rebuilt projects show page

app/assets/stylesheets/pages/_project_show.scss, app/views/projects/show.html.erb
grid for volunteers is not perfect
=> Fix small details showpage

app/views/pages/home.html.erb, app/views/shared/_map.html.erb
inserted projects path to map and work type links
=> creating link paths

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_form.scss, app/controllers/application_controller.rb, app/controllers/bookings_controller.rb, app/controllers/organizations/registrations_controller.rb, app/controllers/organizations/sessions_controller.rb, app/controllers/users/registrations_controller.rb, app/controllers/users/sessions_controller.rb, app/controllers/users_controller.rb, app/views/users/registrations/new.html.erb
- Gem country_select for simple_form added to allow dropdown list of countries in Organization sign up form
- Visitor is now redirected back to previous page after login/sign up, solving the Project page redirect to home issue
- Application Controller updated 
- Bookings Controller updated 
- User Sessions Controller updated
=> User registration page

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_organization_about.scss, app/assets/stylesheets/components/_status.scss, app/assets/stylesheets/components/_tabs.scss, app/assets/stylesheets/components/_user_project_card.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/controllers/organizations_controller.rb, app/controllers/users_controller.rb, app/policies/organization_policy.rb, app/views/organizations/show.html.erb, app/views/shared/_organization_about.html.erb, app/views/shared/_organization_banner.erb, app/views/shared/_organization_banner.html.erb, app/views/shared/_organization_project_cards.html.erb, app/views/shared/_tabs.html.erb, app/views/shared/_user_cards.html.erb, app/views/shared/_user_panel.html.erb, app/views/shared/_user_project_card.html.erb, app/views/users/show.html.erb, config/routes.rb
- Refactored User show page into partials
- Renamed User CSS classes for better semantic
- Refactored Tabs partial so it can be used in both User and Organization show pages
- Created Organization show page
- Created Organization about, banner, and project_cards partials
=> Finished main structure for Organization show panel. Starting JavaScript functionality.

Gemfile, Gemfile.lock, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_project_index.scss, app/controllers/projects_controller.rb, app/models/project.rb, app/views/projects/index.html.erb, app/views/shared/_map.html.erb, db/migrate/20220905183513_add_continent_to_projects.rb, db/schema.rb, db/seeds.rb
Created search on project page, map links(linking to continents) and on project types at home page.
=> Search create

app/controllers/organizations_controller.rb, app/policies/organization_policy.rb, app/views/organizations/projects.html.erb, app/views/organizations/requests.html.erb, app/views/shared/_tabs.html.erb, config/routes.rb
--> Will convert to AJAX rendering with Stimulus
- Custom routes to Organization Projects and Requests
- Custom projects and requests actions created on Organizations controller
- Private method set_organization with redirect to root if @organization returns nil
- View for Organization Projects and Requests
- Starting refactor to implement AJAX
=> Created Organization requests page following the normal flow. 

app/views/shared/_organization_requests.html.erb
Added link to user page at user's name on organization show page (requests section)
=> added link to user name at request

app/controllers/projects_controller.rb, app/views/organizations/show.html.erb, app/views/pages/home.html.erb, app/views/projects/show.html.erb, app/views/shared/_map.html.erb, app/views/users/show.html.erb
- fixed cloudinary
- fixed projects controller
- removed target blanks from links
=> Fixed Cloudinary and projects controler 

config/environments/production.rb
config.active_storage.service = :cloudinary
=> config active storage production to cloudinary

app/models/organization.rb, app/policies/project_policy.rb, app/views/organizations/registrations/new.html.erb, app/views/organizations/show.html.erb, app/views/projects/show.html.erb, app/views/shared/_navbar.html.erb, db/schema.rb
added photos for oranizations and changed avtars
=> added link to in avatars photos

app/assets/stylesheets/components/_form.scss, app/views/organizations/registrations/new.html.erb, app/views/organizations/sessions/new.html.erb, app/views/shared/_navbar.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb
- Added the relative inputs for users and organizations sign up
- Added style to sign up and sign in forms
- Added new links to the navbar
=> Updated login and registration forms with custom classes and their inputs

app/models/project.rb, app/views/organizations/_organization_concluded.html.erb
- Fixed infinite loop in booked_status instance method of Project model
=> Fix booking_status infinite loop in Project model

app/views/organizations/_organization_banner.html.erb
=> put h1 back in org banner and fixed backgroud image problem

app/assets/stylesheets/components/_utilities.scss, app/javascript/controllers/modal_controller.js, app/models/user.rb, app/views/organizations/_organization_requests.html.erb, app/views/shared/_user_panel.html.erb
Created reward system to users based on their booking status
- When a user get a completed booking, he gets his first medal
- When a user completes 5 bookings, he gets another medal
- Both medals come with a modal explaining what it means
=> Creating medals

app/assets/stylesheets/components/_organization_about.scss, app/controllers/organizations/registrations_controller.rb, app/controllers/organizations/sessions_controller.rb, app/controllers/users/registrations_controller.rb, app/controllers/users/sessions_controller.rb, app/views/organizations/_organization_about.html.erb
updated devise sessions and registrations controller to accept About field
=> Fix about organization

app/views/shared/_card.html.erb, app/views/shared/_user_panel.html.erb
fixed attendance button appearance
=> Fix attendance button

app/views/shared/_user_panel.html.erb
=> Final touches on user about section
